In [4]:
import torch

In [5]:
def activation(x):
    
    return 1/(1 + torch.exp(-x))

In [6]:
torch.manual_seed(7)

features = torch.randn((1, 5))

weights = torch.randn_like(features)

bias = torch.randn((1, 1))

In [7]:
features

tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]])

In [4]:
y = activation(torch.sum(features * weights) + bias)

In [5]:
y

tensor([[0.1595]])

In [6]:
weights = weights.view(5, 1)
h = torch.mm(features, weights)

In [7]:
y = activation(torch.sum(h) + bias)

In [8]:
y

tensor([[0.1595]])

In [9]:
torch.manual_seed(7)

features = torch.randn((1, 3))

# Define the size of each layer in our network
n_input = features.shape[1]  # Number of input units, must match number of input features
n_hidden = 2                 # Number of hidden units
n_output = 1                 # Number of output units

# Weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)

# Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

# and bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [21]:
h1 = activation(torch.mm(features, W1.view(3, 2) + B1))
h1

tensor([[0.6980, 0.4553]])

In [24]:
h2 = activation(torch.mm(h1, W2.view(2, 1) + B2))
h2

tensor([[0.3204]])