In [1]:
import torch

In [2]:
def activation(x):
    
    return 1/(1 + torch.exp(-x))

In [3]:
torch.manual_seed(7)

features = torch.rand((1, 3))

n_input = features.shape[1]
n_hidden = 2
n_output = 1

W1 = torch.rand(n_input, n_hidden)

W2 = torch.randn(n_hidden, n_output)

B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [4]:
h = activation(torch.mm(features, W1) + B1)
output = activation(torch.mm(h, W2) + B2)
print(output)

tensor([[0.1451]])


In [5]:
import numpy as np

In [6]:
a = np.random.rand(4, 3)
a

array([[0.63151479, 0.98476116, 0.15781927],
       [0.18542461, 0.82668687, 0.63512167],
       [0.60854568, 0.78213146, 0.81359676],
       [0.99984652, 0.14055224, 0.41979234]])

In [7]:
b = torch.from_numpy(a)
b

tensor([[0.6315, 0.9848, 0.1578],
        [0.1854, 0.8267, 0.6351],
        [0.6085, 0.7821, 0.8136],
        [0.9998, 0.1406, 0.4198]], dtype=torch.float64)

In [8]:
b.numpy()

array([[0.63151479, 0.98476116, 0.15781927],
       [0.18542461, 0.82668687, 0.63512167],
       [0.60854568, 0.78213146, 0.81359676],
       [0.99984652, 0.14055224, 0.41979234]])