In [105]:
import torch

num_entries = 5000

db = torch.rand(num_entries) > 0.5
db

tensor([1, 0, 1,  ..., 0, 1, 1], dtype=torch.uint8)

In [106]:
def get_parallel_db(db, remove_index):
    
    return torch.cat((db[0:remove_index],
                     db[remove_index+1:]))

In [107]:
db[0:5]

tensor([1, 0, 1, 0, 0], dtype=torch.uint8)

In [108]:
get_parallel_db(db, 2)[0:5]

tensor([1, 0, 0, 0, 1], dtype=torch.uint8)

In [109]:
def get_parallel_dbs(db):
    
    parallel_dbs = list()
    
    for i in range(len(db)):
        pdb = get_parallel_db(db, i)
        parallel_dbs.append(pdb)
        
    return parallel_dbs

In [110]:
pdbs = get_parallel_dbs(db)

In [111]:
pdbs

[tensor([0, 1, 0,  ..., 0, 1, 1], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 1, 1], dtype=torch.uint8),
 tensor([1, 0, 0,  ..., 0, 1, 1], dtype=torch.uint8),
 tensor([1, 0, 1,  ..., 0, 1, 1], dtype=torch.uint8),
 tensor([1, 0, 1,  ..., 0, 1, 1], dtype=torch.uint8),
 tensor([1, 0, 1,  ..., 0, 1, 1], dtype=torch.uint8),
 tensor([1, 0, 1,  ..., 0, 1, 1], dtype=torch.uint8),
 tensor([1, 0, 1,  ..., 0, 1, 1], dtype=torch.uint8),
 tensor([1, 0, 1,  ..., 0, 1, 1], dtype=torch.uint8),
 tensor([1, 0, 1,  ..., 0, 1, 1], dtype=torch.uint8),
 tensor([1, 0, 1,  ..., 0, 1, 1], dtype=torch.uint8),
 tensor([1, 0, 1,  ..., 0, 1, 1], dtype=torch.uint8),
 tensor([1, 0, 1,  ..., 0, 1, 1], dtype=torch.uint8),
 tensor([1, 0, 1,  ..., 0, 1, 1], dtype=torch.uint8),
 tensor([1, 0, 1,  ..., 0, 1, 1], dtype=torch.uint8),
 tensor([1, 0, 1,  ..., 0, 1, 1], dtype=torch.uint8),
 tensor([1, 0, 1,  ..., 0, 1, 1], dtype=torch.uint8),
 tensor([1, 0, 1,  ..., 0, 1, 1], dtype=torch.uint8),
 tensor([1, 0, 1,  ..., 0, 1

In [112]:
def create_db_and_parallels(num_entries):
    
    db = torch.rand(num_entries) > 0.5
    pdbs = get_parallel_dbs(db)
    
    return db, pdbs

In [113]:
db, pdbs = create_db_and_parallels(20)

In [114]:
db

tensor([0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1],
       dtype=torch.uint8)

In [115]:
pdbs

[tensor([1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1],
        dtype=torch.uint8),
 tensor([0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1],
        dtype=torch.uint8),
 tensor([0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1],
        dtype=torch.uint8),
 tensor([0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1],
        dtype=torch.uint8),
 tensor([0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1],
        dtype=torch.uint8),
 tensor([0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1],
        dtype=torch.uint8),
 tensor([0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1],
        dtype=torch.uint8),
 tensor([0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1],
        dtype=torch.uint8),
 tensor([0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1],
        dtype=torch.uint8),
 tensor([0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1],
        dtype=torch.uint8),
 tensor([0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,

In [116]:
db, pdbs = create_db_and_parallels(5000)

In [117]:
def query(db):
    return db.sum()

In [118]:
full_db_result = query(db)

In [123]:
max_distance = 0
sensitivity = 0
for pdb in pdbs:
    pdb_result = query(pdb)
    
    db_distance = torch.abs(pdb_result - full_db_result)
    
    if(db_distance > max_distance):
        sensitivity = db_distance

In [125]:
sensitivity

tensor(1)