In [1]:
import torch

num_entries = 5000

db = torch.rand(num_entries) > 0.5
db

tensor([0, 0, 1,  ..., 0, 1, 1], dtype=torch.uint8)

In [3]:
def get_parallel_db(db, remove_index):
    
    return torch.cat((db[0:remove_index],
                     db[remove_index+1:]))

In [6]:
db[0:5]

tensor([0, 0, 1, 1, 0], dtype=torch.uint8)

In [8]:
get_parallel_db(db, 3)[0:5]

tensor([0, 0, 1, 0, 0], dtype=torch.uint8)

In [9]:
def get_parallel_dbs(db):
    
    parallel_dbs = list()
    
    for i in range(len(db)):
        pdb = get_parallel_db(db, i)
        parallel_dbs.append(pdb)
        
    return parallel_dbs

In [12]:
pdbs = get_parallel_dbs(db)

In [13]:
pdbs

[tensor([0, 1, 1,  ..., 0, 1, 1], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 0, 1, 1], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 1, 1], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 1, 1], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 1, 1], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 1, 1], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 1, 1], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 1, 1], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 1, 1], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 1, 1], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 1, 1], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 1, 1], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 1, 1], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 1, 1], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 1, 1], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 1, 1], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 1, 1], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 1, 1], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 1

In [14]:
def create_db_and_parallels(num_entries):
    
    db = torch.rand(num_entries) > 0.5
    pdbs = get_parallel_dbs(db)
    
    return db, pdbs

In [15]:
db, pdbs = create_db_and_parallels(20)

In [16]:
db

tensor([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0],
       dtype=torch.uint8)

In [17]:
pdbs

[tensor([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0],
        dtype=torch.uint8),
 tensor([1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0],
        dtype=torch.uint8),
 tensor([1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0],
        dtype=torch.uint8),
 tensor([1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0],
        dtype=torch.uint8),
 tensor([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0],
        dtype=torch.uint8),
 tensor([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0],
        dtype=torch.uint8),
 tensor([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0],
        dtype=torch.uint8),
 tensor([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0],
        dtype=torch.uint8),
 tensor([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0],
        dtype=torch.uint8),
 tensor([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0],
        dtype=torch.uint8),
 tensor([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,